TILE_ICECROWN_DIRT = FourCC("Idrt")
TILE_ICECROWN_ROUGH_DIRT = FourCC("Idtr")
TILE_ICECROWN_DARK_ICE = FourCC("Idki")
TILE_ICECROWN_BLACK_BRICKS = FourCC("Ibkb")
TILE_ICECROWN_RUNE_BRICKS = FourCC("Irbk")
TILE_ICECROWN_TILED_BRICKS = FourCC("Itbk")
TILE_ICECROWN_ICE = FourCC("Iice")
TILE_ICECROWN_BLACK_SQUARES = FourCC("Ibsq")
TILE_ICECROWN_SNOW = FourCC("Isnw")

TILE_EMPTY = TILE_ICECROWN_DIRT
TILE_FLOOR = TILE_ICECROWN_TILED_BRICKS
TILE_WALL = TILE_ICECROWN_RUNE_BRICKS
TILE_DOOR = TILE_ICECROWN_BLACK_SQUARES
TILE_HALLWAY = TILE_ICECROWN_BLACK_BRICKS